// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	userachievement "github.com/go-jedi/lingramm_backend/internal/domain/user_achievement"
)

// IUnlockAvailableAchievements is an autogenerated mock type for the IUnlockAvailableAchievements type
type IUnlockAvailableAchievements struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IUnlockAvailableAchievements) Execute(ctx context.Context, tx pgx.Tx, telegramID string) ([]userachievement.UnlockAvailableAchievementsResponse, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []userachievement.UnlockAvailableAchievementsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) ([]userachievement.UnlockAvailableAchievementsResponse, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) []userachievement.UnlockAvailableAchievementsResponse); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userachievement.UnlockAvailableAchievementsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUnlockAvailableAchievements creates a new instance of IUnlockAvailableAchievements. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUnlockAvailableAchievements(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUnlockAvailableAchievements {
	mock := &IUnlockAvailableAchievements{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
