// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	userstudiedlanguage "github.com/go-jedi/lingramm_backend/internal/domain/user_studied_language"
)

// IGetByTelegramID is an autogenerated mock type for the IGetByTelegramID type
type IGetByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IGetByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) (userstudiedlanguage.GetByTelegramIDResponse, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userstudiedlanguage.GetByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (userstudiedlanguage.GetByTelegramIDResponse, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) userstudiedlanguage.GetByTelegramIDResponse); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		r0 = ret.Get(0).(userstudiedlanguage.GetByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetByTelegramID creates a new instance of IGetByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetByTelegramID {
	mock := &IGetByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
