// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	user "github.com/go-jedi/lingvogramm_backend/internal/domain/user"
)

// ICreate is an autogenerated mock type for the ICreate type
type ICreate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ICreate) Execute(ctx context.Context, tx pgx.Tx, dto user.CreateDTO) (user.User, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, user.CreateDTO) (user.User, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, user.CreateDTO) user.User); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, user.CreateDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICreate creates a new instance of ICreate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreate {
	mock := &ICreate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
