// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	achievement "github.com/go-jedi/lingramm_backend/internal/domain/achievement"

	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IAllDetail is an autogenerated mock type for the IAllDetail type
type IAllDetail struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx
func (_m *IAllDetail) Execute(ctx context.Context, tx pgx.Tx) ([]achievement.Detail, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []achievement.Detail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) ([]achievement.Detail, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) []achievement.Detail); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]achievement.Detail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAllDetail creates a new instance of IAllDetail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAllDetail(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAllDetail {
	mock := &IAllDetail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
