// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	userbalance "github.com/go-jedi/lingramm_backend/internal/domain/internal_currency/user_balance"
)

// IReduceUserBalance is an autogenerated mock type for the IReduceUserBalance type
type IReduceUserBalance struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *IReduceUserBalance) Execute(ctx context.Context, tx pgx.Tx, dto userbalance.ReduceUserBalanceDTO) (userbalance.UserBalance, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userbalance.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, userbalance.ReduceUserBalanceDTO) (userbalance.UserBalance, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, userbalance.ReduceUserBalanceDTO) userbalance.UserBalance); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Get(0).(userbalance.UserBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, userbalance.ReduceUserBalanceDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIReduceUserBalance creates a new instance of IReduceUserBalance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReduceUserBalance(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReduceUserBalance {
	mock := &IReduceUserBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
