// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dailytask "github.com/go-jedi/lingramm_backend/internal/domain/daily_task"

	mock "github.com/stretchr/testify/mock"
)

// ICreate is an autogenerated mock type for the ICreate type
type ICreate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *ICreate) Execute(ctx context.Context, dto dailytask.CreateDTO) (dailytask.DailyTask, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dailytask.DailyTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dailytask.CreateDTO) (dailytask.DailyTask, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dailytask.CreateDTO) dailytask.DailyTask); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(dailytask.DailyTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dailytask.CreateDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICreate creates a new instance of ICreate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreate {
	mock := &ICreate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
