// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	userdailytask "github.com/go-jedi/lingramm_backend/internal/domain/user_daily_task"
	mock "github.com/stretchr/testify/mock"
)

// IAssignDailyTaskByTelegramID is an autogenerated mock type for the IAssignDailyTaskByTelegramID type
type IAssignDailyTaskByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IAssignDailyTaskByTelegramID) Execute(ctx context.Context, telegramID string) (userdailytask.AssignDailyTaskByTelegramIDResponse, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userdailytask.AssignDailyTaskByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (userdailytask.AssignDailyTaskByTelegramIDResponse, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) userdailytask.AssignDailyTaskByTelegramIDResponse); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(userdailytask.AssignDailyTaskByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAssignDailyTaskByTelegramID creates a new instance of IAssignDailyTaskByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAssignDailyTaskByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAssignDailyTaskByTelegramID {
	mock := &IAssignDailyTaskByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
