// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IExistsAchievementConditionByConditionType is an autogenerated mock type for the IExistsAchievementConditionByConditionType type
type IExistsAchievementConditionByConditionType struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, conditionType
func (_m *IExistsAchievementConditionByConditionType) Execute(ctx context.Context, tx pgx.Tx, conditionType string) (bool, error) {
	ret := _m.Called(ctx, tx, conditionType)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (bool, error)); ok {
		return rf(ctx, tx, conditionType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) bool); ok {
		r0 = rf(ctx, tx, conditionType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, conditionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExistsAchievementConditionByConditionType creates a new instance of IExistsAchievementConditionByConditionType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExistsAchievementConditionByConditionType(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExistsAchievementConditionByConditionType {
	mock := &IExistsAchievementConditionByConditionType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
