version: "2"
run:
  go: 1.25.1
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - err113
    - errcheck
    - exhaustive
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    goconst:
      min-len: 5
      min-occurrences: 4
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: is not allowed from list 'Main'
      - path: (.+)\.go$
        text: a blank import should be only in a main or test package
      - path: (.+)\.go$
        text: File is not properly formatted
      - path: (.+)\.go$
        text: Comment should end in a period
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$