logger:
  is_json: true
  add_source: false
  level: error
  set_file: true
  file_name: logs/app.log
  max_size: 10
  max_backups: 3
  max_age: 7

jwt:
  secret_path: .secret # path to file with secret key
  secret_hash_len: 30
  access_exp_at: 1440 # minutes
  refresh_exp_at: 30 # days

rabbitmq:
  notification:
    consumer:
      url: amqp://guest:guest@localhost:5672/
      timeout_check_connect: 20 # second.
      timeout_publish_message: 5 # second.
      amqp:
        dialer:
          timeout: 5 # second
          keep_alive: 30 # second
        sasl:
          is_plain_auth: true
          plain_auth:
            username: admin
            password: admin
        v_host:
        channel_max: 128
        frame_size: 0
        heart_beat: 10 # second
        properties:
          connection_name: notification
        locale: en_US
        is_dial: true
      exchange:
        name: notification
        kind: direct
        durable: true
        auto_delete: false
        internal: false
        no_wait: false
      queue:
        name:
        durable: false
        auto_delete: true
        exclusive: true
        no_wait: false
        args:
          x_expires: 600000
          x_message_ttl: 600000
      queue_bind:
        exchange: notification
        no_wait: false
      consume:
        consumer:
        auto_ack: false
        exclusive: true
        no_local: false
        no_wait: false
    publisher:
      url: amqp://guest:guest@localhost:5672/
      timeout_check_connect: 20 # second.
      timeout_publish_message: 5 # second.
      query_timeout: 5 # second.
      amqp:
        dialer:
          timeout: 5 # second
          keep_alive: 30 # second
        sasl:
          is_plain_auth: true
          plain_auth:
            username: admin
            password: admin
        v_host:
        channel_max: 128
        frame_size: 0
        heart_beat: 10 # second
        properties:
          connection_name: notification
        locale: en_US
        is_dial: true
      exchange:
        name: notification
        kind: direct
        durable: true
        auto_delete: false
        internal: false
        no_wait: false
      publish:
        exchange: notification
        mandatory: false
        immediate: false
        publishing:
          content_type: application/msgpack
          timestamp: now
          type: notification.create

postgres:
  host: postgres
  user: admin
  password: test
  dbname: lingvogramm_db
  port: 5432
  sslmode: disable
  pool_max_conns: 10
  migrations_dir: file://migrations
  query_timeout: 2 # 2 second

big_cache:
  shards: 512
  life_window: 5 # minutes
  clean_window: 1 # minutes
  max_entries_in_window: 1_000_000
  max_entry_size: 512
  hard_max_cache_size: 600
  verbose: false
  is_on_remove_with_reason: false

redis:
  addr: redis:6379
  password: admin
  db: 0
  dial_timeout: 5 # second
  read_timeout: 3 # second
  write_timeout: 3 # second
  pool_size: 10
  min_idle_conns: 3
  pool_timeout: 4 # second
  max_retries: 3
  min_retry_backoff: 8 # millisecond
  max_retry_backoff: 512 # millisecond
  refresh_token:
    query_timeout: 2 # second
    expiration: 7 # days
  un_delete_file_client:
    query_timeout: 2 # second
    expiration: 0 # days
  un_delete_file_achievement:
    query_timeout: 2 # second
    expiration: 0 # days
  un_delete_file_award:
    query_timeout: 2 # second
    expiration: 0 # days

file_server:
  client_assets:
    path: /images/client*
    url: /images/client
    dir: testdata/file_server/images/client
    max_file_size: 5242880 # 5 MB
    image_quality: 30
    browse: false
    compress: true
    is_next: false
    is_next_ignore_format: .webp
  achievement_assets:
    path: /images/achievement*
    url: /images/achievement
    dir: testdata/file_server/images/achievement
    max_file_size: 5242880 # 5 MB
    image_quality: 30
    browse: false
    compress: true
    is_next: false
    is_next_ignore_format: .webp
  award_assets:
    path: /images/award*
    url: /images/award
    dir: testdata/file_server/images/award
    max_file_size: 5242880 # 5 MB
    image_quality: 30
    browse: false
    compress: true
    is_next: false
    is_next_ignore_format: .webp
  dir_perm: 0755
  file_perm: 0644

cron:
  un_delete_file_client_cleaner:
    sleep_duration: 1440 # minutes
    timeout: 15 # second
  un_delete_file_achievement_cleaner:
    sleep_duration: 720 # minutes
    timeout: 15 # second
  un_delete_file_award_cleaner:
    sleep_duration: 720 # minutes
    timeout: 15 # second

middleware:
  content_length_limiter:
    max_body_size: 5242880

cookie:
  refresh:
    name: refresh
    path: /
    domain: 127.0.0.1
    same_site: lax
    max_age: 2592000 # 30 days
    secure: true
    http_only: true
    partitioned: false
    session_only: false

allowed_ips:
  - 127.0.0.1

swagger_server:
  host: 127.0.0.1
  port: 40050
  shutdown_timeout: 10 # second
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Length
      - Content-Type
      - Accept
      - Authorization
    expose_headers:
      - Content-Length
    max_age: 3600
    allow_credentials: false
    allow_private_network: false

httpserver:
  host: 127.0.0.1
  port: 50050
  shutdown_timeout: 10 # second
  disable_startup_message: true
  enable_prefork: false
  enable_print_routes: false
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Length
      - Content-Type
      - Accept
      - Authorization
    expose_headers:
      - Content-Length
    max_age: 3600
    allow_credentials: false
    allow_private_network: false