volumes:
  postgres_volume:

services:
#  lingvogramm_backend:
#    build: .
#    container_name: lingvogramm_backend
#    restart: always
#    ports:
#      - '50050:50050'
#    volumes:
#      - ./testdata/file_server:/root/testdata/file_server  # mount folder server in container
#    depends_on:
#      - postgres
#      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data