volumes:
  postgres_volume:

services:
#  lingvogramm_backend:
#    build: .
#    container_name: backend
#    restart: always
#    ports:
#      - '50050:50050'
#    volumes:
#      - ./testdata/file_server:/root/testdata/file_server  # mount folder server in container
#    depends_on:
#      - postgres
#      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "63790:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}