// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	localizedtext "github.com/go-jedi/lingramm_backend/internal/domain/localized_text"

	mock "github.com/stretchr/testify/mock"
)

// IGetTextsByLanguage is an autogenerated mock type for the IGetTextsByLanguage type
type IGetTextsByLanguage struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, language
func (_m *IGetTextsByLanguage) Execute(ctx context.Context, language string) (map[string][]localizedtext.LocalizedTexts, error) {
	ret := _m.Called(ctx, language)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 map[string][]localizedtext.LocalizedTexts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string][]localizedtext.LocalizedTexts, error)); ok {
		return rf(ctx, language)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string][]localizedtext.LocalizedTexts); ok {
		r0 = rf(ctx, language)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]localizedtext.LocalizedTexts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, language)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetTextsByLanguage creates a new instance of IGetTextsByLanguage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetTextsByLanguage(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetTextsByLanguage {
	mock := &IGetTextsByLanguage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
