// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	clientassets "github.com/go-jedi/lingramm_backend/internal/domain/file_server/client_assets"

	mock "github.com/stretchr/testify/mock"
)

// IDeleteByID is an autogenerated mock type for the IDeleteByID type
type IDeleteByID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, id
func (_m *IDeleteByID) Execute(ctx context.Context, id int64) (clientassets.ClientAssets, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 clientassets.ClientAssets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (clientassets.ClientAssets, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) clientassets.ClientAssets); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(clientassets.ClientAssets)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDeleteByID creates a new instance of IDeleteByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDeleteByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDeleteByID {
	mock := &IDeleteByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
