// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/go-jedi/lingramm_backend/internal/domain/notification"
	mock "github.com/stretchr/testify/mock"
)

// IPublisher is an autogenerated mock type for the IPublisher type
type IPublisher struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *IPublisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Execute provides a mock function with given fields: ctx, telegramID, data
func (_m *IPublisher) Execute(ctx context.Context, telegramID string, data notification.SendNotificationDTO) error {
	ret := _m.Called(ctx, telegramID, data)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notification.SendNotificationDTO) error); ok {
		r0 = rf(ctx, telegramID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPublisher creates a new instance of IPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPublisher {
	mock := &IPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
