// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	experiencepoint "github.com/go-jedi/lingramm_backend/internal/domain/experience_point"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IGetLeaderboardTopWeekForUser is an autogenerated mock type for the IGetLeaderboardTopWeekForUser type
type IGetLeaderboardTopWeekForUser struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *IGetLeaderboardTopWeekForUser) Execute(ctx context.Context, tx pgx.Tx, dto experiencepoint.GetLeaderboardTopWeekForUserDTO) ([]experiencepoint.GetLeaderboardTopWeekForUserResponse, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []experiencepoint.GetLeaderboardTopWeekForUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.GetLeaderboardTopWeekForUserDTO) ([]experiencepoint.GetLeaderboardTopWeekForUserResponse, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.GetLeaderboardTopWeekForUserDTO) []experiencepoint.GetLeaderboardTopWeekForUserResponse); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]experiencepoint.GetLeaderboardTopWeekForUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, experiencepoint.GetLeaderboardTopWeekForUserDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetLeaderboardTopWeekForUser creates a new instance of IGetLeaderboardTopWeekForUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetLeaderboardTopWeekForUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetLeaderboardTopWeekForUser {
	mock := &IGetLeaderboardTopWeekForUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
