// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	userdailytask "github.com/go-jedi/lingramm_backend/internal/domain/user_daily_task"
)

// IGetCurrentDailyTaskByTelegramID is an autogenerated mock type for the IGetCurrentDailyTaskByTelegramID type
type IGetCurrentDailyTaskByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IGetCurrentDailyTaskByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) (userdailytask.GetCurrentDailyTaskByTelegramIDResponse, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userdailytask.GetCurrentDailyTaskByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (userdailytask.GetCurrentDailyTaskByTelegramIDResponse, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) userdailytask.GetCurrentDailyTaskByTelegramIDResponse); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		r0 = ret.Get(0).(userdailytask.GetCurrentDailyTaskByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetCurrentDailyTaskByTelegramID creates a new instance of IGetCurrentDailyTaskByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetCurrentDailyTaskByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetCurrentDailyTaskByTelegramID {
	mock := &IGetCurrentDailyTaskByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
