// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	eventtype "github.com/go-jedi/lingramm_backend/internal/domain/event_type"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IGetByName is an autogenerated mock type for the IGetByName type
type IGetByName struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, name
func (_m *IGetByName) Execute(ctx context.Context, tx pgx.Tx, name string) (eventtype.EventType, error) {
	ret := _m.Called(ctx, tx, name)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 eventtype.EventType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (eventtype.EventType, error)); ok {
		return rf(ctx, tx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) eventtype.EventType); ok {
		r0 = rf(ctx, tx, name)
	} else {
		r0 = ret.Get(0).(eventtype.EventType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetByName creates a new instance of IGetByName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetByName(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetByName {
	mock := &IGetByName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
