// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	level "github.com/go-jedi/lingramm_backend/internal/domain/level"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// ICreateUserLevelHistory is an autogenerated mock type for the ICreateUserLevelHistory type
type ICreateUserLevelHistory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ICreateUserLevelHistory) Execute(ctx context.Context, tx pgx.Tx, dto level.CreateUserLevelHistoryDTO) (level.UserLevelHistory, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 level.UserLevelHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, level.CreateUserLevelHistoryDTO) (level.UserLevelHistory, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, level.CreateUserLevelHistoryDTO) level.UserLevelHistory); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Get(0).(level.UserLevelHistory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, level.CreateUserLevelHistoryDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICreateUserLevelHistory creates a new instance of ICreateUserLevelHistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateUserLevelHistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateUserLevelHistory {
	mock := &ICreateUserLevelHistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
