// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/go-jedi/lingramm_backend/internal/domain/notification"
	mock "github.com/stretchr/testify/mock"
)

// IAllByTelegramID is an autogenerated mock type for the IAllByTelegramID type
type IAllByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IAllByTelegramID) Execute(ctx context.Context, telegramID string) ([]notification.Notification, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]notification.Notification, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []notification.Notification); ok {
		r0 = rf(ctx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAllByTelegramID creates a new instance of IAllByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAllByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAllByTelegramID {
	mock := &IAllByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
