// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IExistsByName is an autogenerated mock type for the IExistsByName type
type IExistsByName struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, name
func (_m *IExistsByName) Execute(ctx context.Context, tx pgx.Tx, name string) (bool, error) {
	ret := _m.Called(ctx, tx, name)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (bool, error)); ok {
		return rf(ctx, tx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) bool); ok {
		r0 = rf(ctx, tx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExistsByName creates a new instance of IExistsByName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExistsByName(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExistsByName {
	mock := &IExistsByName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
