// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/go-jedi/lingramm_backend/internal/domain/notification"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IAllPendingBeforeByTelegramID is an autogenerated mock type for the IAllPendingBeforeByTelegramID type
type IAllPendingBeforeByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID, t0
func (_m *IAllPendingBeforeByTelegramID) Execute(ctx context.Context, telegramID string, t0 time.Time) ([]notification.Notification, error) {
	ret := _m.Called(ctx, telegramID, t0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]notification.Notification, error)); ok {
		return rf(ctx, telegramID, t0)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []notification.Notification); ok {
		r0 = rf(ctx, telegramID, t0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, telegramID, t0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAllPendingBeforeByTelegramID creates a new instance of IAllPendingBeforeByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAllPendingBeforeByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAllPendingBeforeByTelegramID {
	mock := &IAllPendingBeforeByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
