// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/go-jedi/lingramm_backend/internal/domain/event"

	mock "github.com/stretchr/testify/mock"
)

// ICreateEvents is an autogenerated mock type for the ICreateEvents type
type ICreateEvents struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *ICreateEvents) Execute(ctx context.Context, dto event.CreateEventsDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.CreateEventsDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICreateEvents creates a new instance of ICreateEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateEvents(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateEvents {
	mock := &ICreateEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
