// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	notification "github.com/go-jedi/lingramm_backend/internal/domain/notification"

	pgx "github.com/jackc/pgx/v5"
)

// ICreateNotifications is an autogenerated mock type for the ICreateNotifications type
type ICreateNotifications struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ICreateNotifications) Execute(ctx context.Context, tx pgx.Tx, dto []notification.CreateDTO) ([]notification.Notification, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, []notification.CreateDTO) ([]notification.Notification, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, []notification.CreateDTO) []notification.Notification); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, []notification.CreateDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICreateNotifications creates a new instance of ICreateNotifications. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateNotifications(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateNotifications {
	mock := &ICreateNotifications{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
