// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/go-jedi/lingramm_backend/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"

	user "github.com/go-jedi/lingramm_backend/internal/domain/user"
)

// ISignIn is an autogenerated mock type for the ISignIn type
type ISignIn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *ISignIn) Execute(ctx context.Context, dto auth.SignInDTO) (user.User, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.SignInDTO) (user.User, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.SignInDTO) user.User); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.SignInDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISignIn creates a new instance of ISignIn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISignIn(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISignIn {
	mock := &ISignIn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
