// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	subscription "github.com/go-jedi/lingramm_backend/internal/domain/subscription"
)

// ICreateSubscriptionHistory is an autogenerated mock type for the ICreateSubscriptionHistory type
type ICreateSubscriptionHistory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ICreateSubscriptionHistory) Execute(ctx context.Context, tx pgx.Tx, dto subscription.CreateSubscriptionHistoryDTO) error {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, subscription.CreateSubscriptionHistoryDTO) error); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICreateSubscriptionHistory creates a new instance of ICreateSubscriptionHistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateSubscriptionHistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateSubscriptionHistory {
	mock := &ICreateSubscriptionHistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
