// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/go-jedi/lingramm_backend/internal/domain/notification"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IAllPendingByTelegramID is an autogenerated mock type for the IAllPendingByTelegramID type
type IAllPendingByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IAllPendingByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) ([]notification.Notification, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) ([]notification.Notification, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) []notification.Notification); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAllPendingByTelegramID creates a new instance of IAllPendingByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAllPendingByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAllPendingByTelegramID {
	mock := &IAllPendingByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
