// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	userstats "github.com/go-jedi/lingramm_backend/internal/domain/user_stats"
)

// IGetLevelByTelegramID is an autogenerated mock type for the IGetLevelByTelegramID type
type IGetLevelByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IGetLevelByTelegramID) Execute(ctx context.Context, telegramID string) (userstats.GetLevelByTelegramIDResponse, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userstats.GetLevelByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (userstats.GetLevelByTelegramIDResponse, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) userstats.GetLevelByTelegramIDResponse); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(userstats.GetLevelByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetLevelByTelegramID creates a new instance of IGetLevelByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetLevelByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetLevelByTelegramID {
	mock := &IGetLevelByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
