// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	awardassets "github.com/go-jedi/lingramm_backend/internal/domain/file_server/award_assets"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// IAwardAssets is an autogenerated mock type for the IAwardAssets type
type IAwardAssets struct {
	mock.Mock
}

// UploadAndConvertToWebP provides a mock function with given fields: ctx, fileHeader
func (_m *IAwardAssets) UploadAndConvertToWebP(ctx context.Context, fileHeader *multipart.FileHeader) (awardassets.UploadAndConvertToWebpResponse, error) {
	ret := _m.Called(ctx, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for UploadAndConvertToWebP")
	}

	var r0 awardassets.UploadAndConvertToWebpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (awardassets.UploadAndConvertToWebpResponse, error)); ok {
		return rf(ctx, fileHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) awardassets.UploadAndConvertToWebpResponse); ok {
		r0 = rf(ctx, fileHeader)
	} else {
		r0 = ret.Get(0).(awardassets.UploadAndConvertToWebpResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, fileHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAwardAssets creates a new instance of IAwardAssets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAwardAssets(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAwardAssets {
	mock := &IAwardAssets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
