// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISwaggerServer is an autogenerated mock type for the ISwaggerServer type
type ISwaggerServer struct {
	mock.Mock
}

// Start provides a mock function with no fields
func (_m *ISwaggerServer) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISwaggerServer creates a new instance of ISwaggerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISwaggerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISwaggerServer {
	mock := &ISwaggerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
