// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	achievement "github.com/go-jedi/lingramm_backend/internal/domain/achievement"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IDeleteAchievementByID is an autogenerated mock type for the IDeleteAchievementByID type
type IDeleteAchievementByID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, id
func (_m *IDeleteAchievementByID) Execute(ctx context.Context, tx pgx.Tx, id int64) (achievement.Achievement, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 achievement.Achievement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (achievement.Achievement, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) achievement.Achievement); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(achievement.Achievement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDeleteAchievementByID creates a new instance of IDeleteAchievementByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDeleteAchievementByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDeleteAchievementByID {
	mock := &IDeleteAchievementByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
