// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	clientassets "github.com/go-jedi/lingvogramm_backend/internal/domain/file_server/client_assets"

	mock "github.com/stretchr/testify/mock"
)

// IAll is an autogenerated mock type for the IAll type
type IAll struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *IAll) Execute(ctx context.Context) ([]clientassets.ClientAssets, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []clientassets.ClientAssets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]clientassets.ClientAssets, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []clientassets.ClientAssets); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clientassets.ClientAssets)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAll creates a new instance of IAll. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAll(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAll {
	mock := &IAll{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
