// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	user "github.com/go-jedi/lingramm_backend/internal/domain/user"
)

// IGetByUUID is an autogenerated mock type for the IGetByUUID type
type IGetByUUID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, uuid
func (_m *IGetByUUID) Execute(ctx context.Context, tx pgx.Tx, uuid string) (user.User, error) {
	ret := _m.Called(ctx, tx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (user.User, error)); ok {
		return rf(ctx, tx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) user.User); ok {
		r0 = rf(ctx, tx, uuid)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetByUUID creates a new instance of IGetByUUID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetByUUID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetByUUID {
	mock := &IGetByUUID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
