// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	achievementassets "github.com/go-jedi/lingramm_backend/internal/domain/file_server/achievement_assets"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// IAchievementAssets is an autogenerated mock type for the IAchievementAssets type
type IAchievementAssets struct {
	mock.Mock
}

// UploadAndConvertToWebP provides a mock function with given fields: ctx, fileHeader
func (_m *IAchievementAssets) UploadAndConvertToWebP(ctx context.Context, fileHeader *multipart.FileHeader) (achievementassets.UploadAndConvertToWebpResponse, error) {
	ret := _m.Called(ctx, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for UploadAndConvertToWebP")
	}

	var r0 achievementassets.UploadAndConvertToWebpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (achievementassets.UploadAndConvertToWebpResponse, error)); ok {
		return rf(ctx, fileHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) achievementassets.UploadAndConvertToWebpResponse); ok {
		r0 = rf(ctx, fileHeader)
	} else {
		r0 = ret.Get(0).(achievementassets.UploadAndConvertToWebpResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, fileHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAchievementAssets creates a new instance of IAchievementAssets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAchievementAssets(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAchievementAssets {
	mock := &IAchievementAssets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
