// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	userstats "github.com/go-jedi/lingramm_backend/internal/domain/user_stats"
)

// IGetLevelInfoByTelegramID is an autogenerated mock type for the IGetLevelInfoByTelegramID type
type IGetLevelInfoByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IGetLevelInfoByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) (userstats.GetLevelInfoByTelegramIDResponse, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userstats.GetLevelInfoByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (userstats.GetLevelInfoByTelegramIDResponse, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) userstats.GetLevelInfoByTelegramIDResponse); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		r0 = ret.Get(0).(userstats.GetLevelInfoByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetLevelInfoByTelegramID creates a new instance of IGetLevelInfoByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetLevelInfoByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetLevelInfoByTelegramID {
	mock := &IGetLevelInfoByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
