// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	userdailytask "github.com/go-jedi/lingramm_backend/internal/domain/user_daily_task"
)

// ISyncUserDailyTaskProgress is an autogenerated mock type for the ISyncUserDailyTaskProgress type
type ISyncUserDailyTaskProgress struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ISyncUserDailyTaskProgress) Execute(ctx context.Context, tx pgx.Tx, dto userdailytask.SyncUserDailyTaskProgressDTO) error {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, userdailytask.SyncUserDailyTaskProgressDTO) error); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISyncUserDailyTaskProgress creates a new instance of ISyncUserDailyTaskProgress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISyncUserDailyTaskProgress(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISyncUserDailyTaskProgress {
	mock := &ISyncUserDailyTaskProgress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
