// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/go-jedi/lingramm_backend/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// IRefresh is an autogenerated mock type for the IRefresh type
type IRefresh struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *IRefresh) Execute(ctx context.Context, dto auth.RefreshDTO) (auth.RefreshResponse, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 auth.RefreshResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RefreshDTO) (auth.RefreshResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RefreshDTO) auth.RefreshResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(auth.RefreshResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RefreshDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRefresh creates a new instance of IRefresh. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRefresh(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRefresh {
	mock := &IRefresh{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
