// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	level "github.com/go-jedi/lingramm_backend/internal/domain/level"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IBackFillMissingLevelHistoryByTelegramID is an autogenerated mock type for the IBackFillMissingLevelHistoryByTelegramID type
type IBackFillMissingLevelHistoryByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IBackFillMissingLevelHistoryByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) (level.BackFillMissingLevelHistoryByTelegramIDResponse, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 level.BackFillMissingLevelHistoryByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (level.BackFillMissingLevelHistoryByTelegramIDResponse, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) level.BackFillMissingLevelHistoryByTelegramIDResponse); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		r0 = ret.Get(0).(level.BackFillMissingLevelHistoryByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIBackFillMissingLevelHistoryByTelegramID creates a new instance of IBackFillMissingLevelHistoryByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBackFillMissingLevelHistoryByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBackFillMissingLevelHistoryByTelegramID {
	mock := &IBackFillMissingLevelHistoryByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
