// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	clientassets "github.com/go-jedi/lingramm_backend/internal/domain/file_server/client_assets"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// IClientAssets is an autogenerated mock type for the IClientAssets type
type IClientAssets struct {
	mock.Mock
}

// UploadAndConvertToWebP provides a mock function with given fields: ctx, fileHeader
func (_m *IClientAssets) UploadAndConvertToWebP(ctx context.Context, fileHeader *multipart.FileHeader) (clientassets.UploadAndConvertToWebpResponse, error) {
	ret := _m.Called(ctx, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for UploadAndConvertToWebP")
	}

	var r0 clientassets.UploadAndConvertToWebpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (clientassets.UploadAndConvertToWebpResponse, error)); ok {
		return rf(ctx, fileHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) clientassets.UploadAndConvertToWebpResponse); ok {
		r0 = rf(ctx, fileHeader)
	} else {
		r0 = ret.Get(0).(clientassets.UploadAndConvertToWebpResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, fileHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIClientAssets creates a new instance of IClientAssets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientAssets(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientAssets {
	mock := &IClientAssets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
