// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IExistsByID is an autogenerated mock type for the IExistsByID type
type IExistsByID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, id
func (_m *IExistsByID) Execute(ctx context.Context, tx pgx.Tx, id int64) (bool, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (bool, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) bool); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExistsByID creates a new instance of IExistsByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExistsByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExistsByID {
	mock := &IExistsByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
