// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	experiencepoint "github.com/go-jedi/lingramm_backend/internal/domain/experience_point"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IGetLeaderboardTopWeek is an autogenerated mock type for the IGetLeaderboardTopWeek type
type IGetLeaderboardTopWeek struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *IGetLeaderboardTopWeek) Execute(ctx context.Context, tx pgx.Tx, dto experiencepoint.GetLeaderboardTopWeekDTO) ([]experiencepoint.GetLeaderboardTopWeekResponse, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []experiencepoint.GetLeaderboardTopWeekResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.GetLeaderboardTopWeekDTO) ([]experiencepoint.GetLeaderboardTopWeekResponse, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.GetLeaderboardTopWeekDTO) []experiencepoint.GetLeaderboardTopWeekResponse); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]experiencepoint.GetLeaderboardTopWeekResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, experiencepoint.GetLeaderboardTopWeekDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetLeaderboardTopWeek creates a new instance of IGetLeaderboardTopWeek. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetLeaderboardTopWeek(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetLeaderboardTopWeek {
	mock := &IGetLeaderboardTopWeek{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
