// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/go-jedi/lingramm_backend/internal/domain/notification"
	mock "github.com/stretchr/testify/mock"
)

// IConsumer is an autogenerated mock type for the IConsumer type
type IConsumer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *IConsumer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Execute provides a mock function with given fields: ctx, telegramID, fn
func (_m *IConsumer) Execute(ctx context.Context, telegramID string, fn func(notification.SendNotificationDTO) error) error {
	ret := _m.Called(ctx, telegramID, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(notification.SendNotificationDTO) error) error); ok {
		r0 = rf(ctx, telegramID, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIConsumer creates a new instance of IConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IConsumer {
	mock := &IConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
