// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IExistsTextTranslation is an autogenerated mock type for the IExistsTextTranslation type
type IExistsTextTranslation struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, contentID, language
func (_m *IExistsTextTranslation) Execute(ctx context.Context, tx pgx.Tx, contentID int64, language string) (bool, error) {
	ret := _m.Called(ctx, tx, contentID, language)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, string) (bool, error)); ok {
		return rf(ctx, tx, contentID, language)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, string) bool); ok {
		r0 = rf(ctx, tx, contentID, language)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64, string) error); ok {
		r1 = rf(ctx, tx, contentID, language)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExistsTextTranslation creates a new instance of IExistsTextTranslation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExistsTextTranslation(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExistsTextTranslation {
	mock := &IExistsTextTranslation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
