// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	userstudiedlanguage "github.com/go-jedi/lingramm_backend/internal/domain/user_studied_language"
)

// IUpdate is an autogenerated mock type for the IUpdate type
type IUpdate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *IUpdate) Execute(ctx context.Context, tx pgx.Tx, dto userstudiedlanguage.UpdateDTO) (userstudiedlanguage.UserStudiedLanguage, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userstudiedlanguage.UserStudiedLanguage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, userstudiedlanguage.UpdateDTO) (userstudiedlanguage.UserStudiedLanguage, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, userstudiedlanguage.UpdateDTO) userstudiedlanguage.UserStudiedLanguage); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Get(0).(userstudiedlanguage.UserStudiedLanguage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, userstudiedlanguage.UpdateDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUpdate creates a new instance of IUpdate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUpdate(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUpdate {
	mock := &IUpdate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
