// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	subscription "github.com/go-jedi/lingramm_backend/internal/domain/subscription"
)

// IGetByTelegramID is an autogenerated mock type for the IGetByTelegramID type
type IGetByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IGetByTelegramID) Execute(ctx context.Context, telegramID string) (subscription.Subscription, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 subscription.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (subscription.Subscription, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) subscription.Subscription); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(subscription.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetByTelegramID creates a new instance of IGetByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetByTelegramID {
	mock := &IGetByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
