// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	achievement "github.com/go-jedi/lingramm_backend/internal/domain/achievement"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IDeleteAchievementConditionByAchievementID is an autogenerated mock type for the IDeleteAchievementConditionByAchievementID type
type IDeleteAchievementConditionByAchievementID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, achievementID
func (_m *IDeleteAchievementConditionByAchievementID) Execute(ctx context.Context, tx pgx.Tx, achievementID int64) (achievement.Condition, error) {
	ret := _m.Called(ctx, tx, achievementID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 achievement.Condition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (achievement.Condition, error)); ok {
		return rf(ctx, tx, achievementID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) achievement.Condition); ok {
		r0 = rf(ctx, tx, achievementID)
	} else {
		r0 = ret.Get(0).(achievement.Condition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, achievementID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDeleteAchievementConditionByAchievementID creates a new instance of IDeleteAchievementConditionByAchievementID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDeleteAchievementConditionByAchievementID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDeleteAchievementConditionByAchievementID {
	mock := &IDeleteAchievementConditionByAchievementID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
