// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// ISyncUserStatsFromXPEventsByTelegramID is an autogenerated mock type for the ISyncUserStatsFromXPEventsByTelegramID type
type ISyncUserStatsFromXPEventsByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *ISyncUserStatsFromXPEventsByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) error {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISyncUserStatsFromXPEventsByTelegramID creates a new instance of ISyncUserStatsFromXPEventsByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISyncUserStatsFromXPEventsByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISyncUserStatsFromXPEventsByTelegramID {
	mock := &ISyncUserStatsFromXPEventsByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
