// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	achievement "github.com/go-jedi/lingramm_backend/internal/domain/achievement"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// ICreateAchievement is an autogenerated mock type for the ICreateAchievement type
type ICreateAchievement struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ICreateAchievement) Execute(ctx context.Context, tx pgx.Tx, dto achievement.CreateAchievementDTO) (achievement.Achievement, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 achievement.Achievement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, achievement.CreateAchievementDTO) (achievement.Achievement, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, achievement.CreateAchievementDTO) achievement.Achievement); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Get(0).(achievement.Achievement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, achievement.CreateAchievementDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICreateAchievement creates a new instance of ICreateAchievement. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateAchievement(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateAchievement {
	mock := &ICreateAchievement{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
