// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IEnsureStreakDaysIncrementToday is an autogenerated mock type for the IEnsureStreakDaysIncrementToday type
type IEnsureStreakDaysIncrementToday struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IEnsureStreakDaysIncrementToday) Execute(ctx context.Context, telegramID string) error {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIEnsureStreakDaysIncrementToday creates a new instance of IEnsureStreakDaysIncrementToday. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEnsureStreakDaysIncrementToday(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEnsureStreakDaysIncrementToday {
	mock := &IEnsureStreakDaysIncrementToday{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
