// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	userachievement "github.com/go-jedi/lingramm_backend/internal/domain/user_achievement"
)

// IAllDetailByTelegramID is an autogenerated mock type for the IAllDetailByTelegramID type
type IAllDetailByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID
func (_m *IAllDetailByTelegramID) Execute(ctx context.Context, tx pgx.Tx, telegramID string) ([]userachievement.Detail, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []userachievement.Detail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) ([]userachievement.Detail, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) []userachievement.Detail); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userachievement.Detail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAllDetailByTelegramID creates a new instance of IAllDetailByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAllDetailByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAllDetailByTelegramID {
	mock := &IAllDetailByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
