// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	experiencepoint "github.com/go-jedi/lingramm_backend/internal/domain/experience_point"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// ILeaderboardWeeksProcessBatch is an autogenerated mock type for the ILeaderboardWeeksProcessBatch type
type ILeaderboardWeeksProcessBatch struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ILeaderboardWeeksProcessBatch) Execute(ctx context.Context, tx pgx.Tx, dto experiencepoint.LeaderboardWeeksProcessBatchDTO) (experiencepoint.LeaderboardWeeksProcessBatchResponse, error) {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 experiencepoint.LeaderboardWeeksProcessBatchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.LeaderboardWeeksProcessBatchDTO) (experiencepoint.LeaderboardWeeksProcessBatchResponse, error)); ok {
		return rf(ctx, tx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.LeaderboardWeeksProcessBatchDTO) experiencepoint.LeaderboardWeeksProcessBatchResponse); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Get(0).(experiencepoint.LeaderboardWeeksProcessBatchResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, experiencepoint.LeaderboardWeeksProcessBatchDTO) error); ok {
		r1 = rf(ctx, tx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewILeaderboardWeeksProcessBatch creates a new instance of ILeaderboardWeeksProcessBatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILeaderboardWeeksProcessBatch(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILeaderboardWeeksProcessBatch {
	mock := &ILeaderboardWeeksProcessBatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
