// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	awardassets "github.com/go-jedi/lingramm_backend/internal/domain/file_server/award_assets"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IAll is an autogenerated mock type for the IAll type
type IAll struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx
func (_m *IAll) Execute(ctx context.Context, tx pgx.Tx) ([]awardassets.AwardAssets, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []awardassets.AwardAssets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) ([]awardassets.AwardAssets, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) []awardassets.AwardAssets); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]awardassets.AwardAssets)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAll creates a new instance of IAll. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAll(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAll {
	mock := &IAll{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
