// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	userdailytask "github.com/go-jedi/lingramm_backend/internal/domain/user_daily_task"
)

// IGetDailyTaskWeekSummaryByTelegramID is an autogenerated mock type for the IGetDailyTaskWeekSummaryByTelegramID type
type IGetDailyTaskWeekSummaryByTelegramID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IGetDailyTaskWeekSummaryByTelegramID) Execute(ctx context.Context, telegramID string) ([]userdailytask.GetDailyTaskWeekSummaryByTelegramIDResponse, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []userdailytask.GetDailyTaskWeekSummaryByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]userdailytask.GetDailyTaskWeekSummaryByTelegramIDResponse, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []userdailytask.GetDailyTaskWeekSummaryByTelegramIDResponse); ok {
		r0 = rf(ctx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userdailytask.GetDailyTaskWeekSummaryByTelegramIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetDailyTaskWeekSummaryByTelegramID creates a new instance of IGetDailyTaskWeekSummaryByTelegramID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetDailyTaskWeekSummaryByTelegramID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetDailyTaskWeekSummaryByTelegramID {
	mock := &IGetDailyTaskWeekSummaryByTelegramID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
