// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	admin "github.com/go-jedi/lingramm_backend/internal/domain/admin"

	mock "github.com/stretchr/testify/mock"
)

// IAdmin is an autogenerated mock type for the IAdmin type
type IAdmin struct {
	mock.Mock
}

// All provides a mock function with no fields
func (_m *IAdmin) All() ([]admin.Admin, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []admin.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]admin.Admin, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []admin.Admin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]admin.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: key
func (_m *IAdmin) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: key
func (_m *IAdmin) Exists(key string) (bool, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: key
func (_m *IAdmin) Get(key string) (admin.Admin, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 admin.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (admin.Admin, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) admin.Admin); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(admin.Admin)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, val
func (_m *IAdmin) Set(key string, val admin.Admin) error {
	ret := _m.Called(key, val)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, admin.Admin) error); ok {
		r0 = rf(key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAdmin creates a new instance of IAdmin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdmin(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdmin {
	mock := &IAdmin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
