// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IExists is an autogenerated mock type for the IExists type
type IExists struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, telegramID, username
func (_m *IExists) Execute(ctx context.Context, tx pgx.Tx, telegramID string, username string) (bool, error) {
	ret := _m.Called(ctx, tx, telegramID, username)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, string) (bool, error)); ok {
		return rf(ctx, tx, telegramID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, string) bool); ok {
		r0 = rf(ctx, tx, telegramID, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string, string) error); ok {
		r1 = rf(ctx, tx, telegramID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExists creates a new instance of IExists. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExists(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExists {
	mock := &IExists{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
