// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	balancetransactionevent "github.com/go-jedi/lingramm_backend/internal/domain/internal_currency/balance_transaction_event"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IGetBalanceTransactionEventByCode is an autogenerated mock type for the IGetBalanceTransactionEventByCode type
type IGetBalanceTransactionEventByCode struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, code
func (_m *IGetBalanceTransactionEventByCode) Execute(ctx context.Context, tx pgx.Tx, code string) (balancetransactionevent.BalanceTransactionEvent, error) {
	ret := _m.Called(ctx, tx, code)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 balancetransactionevent.BalanceTransactionEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (balancetransactionevent.BalanceTransactionEvent, error)); ok {
		return rf(ctx, tx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) balancetransactionevent.BalanceTransactionEvent); ok {
		r0 = rf(ctx, tx, code)
	} else {
		r0 = ret.Get(0).(balancetransactionevent.BalanceTransactionEvent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetBalanceTransactionEventByCode creates a new instance of IGetBalanceTransactionEventByCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetBalanceTransactionEventByCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetBalanceTransactionEventByCode {
	mock := &IGetBalanceTransactionEventByCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
