// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	userbalance "github.com/go-jedi/lingramm_backend/internal/domain/internal_currency/user_balance"
)

// IGetUserBalance is an autogenerated mock type for the IGetUserBalance type
type IGetUserBalance struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, telegramID
func (_m *IGetUserBalance) Execute(ctx context.Context, telegramID string) (userbalance.UserBalance, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 userbalance.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (userbalance.UserBalance, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) userbalance.UserBalance); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(userbalance.UserBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGetUserBalance creates a new instance of IGetUserBalance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetUserBalance(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetUserBalance {
	mock := &IGetUserBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
