// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	localizedtext "github.com/go-jedi/lingramm_backend/internal/domain/localized_text"

	mock "github.com/stretchr/testify/mock"
)

// ICreateTextContent is an autogenerated mock type for the ICreateTextContent type
type ICreateTextContent struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *ICreateTextContent) Execute(ctx context.Context, dto localizedtext.CreateTextContentDTO) (localizedtext.TextContents, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 localizedtext.TextContents
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, localizedtext.CreateTextContentDTO) (localizedtext.TextContents, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, localizedtext.CreateTextContentDTO) localizedtext.TextContents); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(localizedtext.TextContents)
	}

	if rf, ok := ret.Get(1).(func(context.Context, localizedtext.CreateTextContentDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICreateTextContent creates a new instance of ICreateTextContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateTextContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateTextContent {
	mock := &ICreateTextContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
