// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	auth "github.com/go-jedi/lingramm_backend/internal/domain/auth"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ICheck is an autogenerated mock type for the ICheck type
type ICheck struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *ICheck) Execute(ctx context.Context, dto auth.CheckDTO) (auth.CheckResponse, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 auth.CheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.CheckDTO) (auth.CheckResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.CheckDTO) auth.CheckResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(auth.CheckResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.CheckDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICheck creates a new instance of ICheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICheck {
	mock := &ICheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
