// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	experiencepoint "github.com/go-jedi/lingramm_backend/internal/domain/experience_point"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// ICreateXPEvents is an autogenerated mock type for the ICreateXPEvents type
type ICreateXPEvents struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, dto
func (_m *ICreateXPEvents) Execute(ctx context.Context, tx pgx.Tx, dto experiencepoint.CreateXPEventDTO) error {
	ret := _m.Called(ctx, tx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, experiencepoint.CreateXPEventDTO) error); ok {
		r0 = rf(ctx, tx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICreateXPEvents creates a new instance of ICreateXPEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateXPEvents(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateXPEvents {
	mock := &ICreateXPEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
