// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// IUpdateStatus is an autogenerated mock type for the IUpdateStatus type
type IUpdateStatus struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, id, status
func (_m *IUpdateStatus) Execute(ctx context.Context, tx pgx.Tx, id int64, status string) error {
	ret := _m.Called(ctx, tx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, string) error); ok {
		r0 = rf(ctx, tx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIUpdateStatus creates a new instance of IUpdateStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUpdateStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUpdateStatus {
	mock := &IUpdateStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
