// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	localizedtext "github.com/go-jedi/lingramm_backend/internal/domain/localized_text"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// IDeleteTextTranslationByID is an autogenerated mock type for the IDeleteTextTranslationByID type
type IDeleteTextTranslationByID struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, tx, id
func (_m *IDeleteTextTranslationByID) Execute(ctx context.Context, tx pgx.Tx, id int64) (localizedtext.TextTranslations, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 localizedtext.TextTranslations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (localizedtext.TextTranslations, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) localizedtext.TextTranslations); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(localizedtext.TextTranslations)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDeleteTextTranslationByID creates a new instance of IDeleteTextTranslationByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDeleteTextTranslationByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDeleteTextTranslationByID {
	mock := &IDeleteTextTranslationByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
